CardinalityEstimator.o : CardinalityEstimator.cpp CardinalityEstimator.h
	g++ -c -std=c++11 CardinalityEstimator.cpp
debs_challenge_util.o : debs_challenge_util.cpp debs_challenge_util.h
	g++ -c -std=c++11 debs_challenge_util.cpp

MurmurHash3.o : MurmurHash3.cpp MurmurHash3.h
	g++ -c -std=c++11 MurmurHash3.cpp

BitTrickBox.o : BitTrickBox.cpp BitTrickBox.h
	g++ -c -std=c++11 BitTrickBox.cpp

clean :