CC = g++
#CC = /opt/rh/devtoolset-2/root/usr/bin/g++
#CC = /usr/local/gcc-6.3.0/bin/g++
FLAGS = -std=c++11 -g -O3 -Wall -Wextra -pthread
LD = g++
LDFLAGS = 
AR = ar
RM = rm
ECHO = echo
SHELL = /bin/sh
.SILENT =
LIBS = -lpthread -lm
